plugins {
    id 'com.android.application'
}

android {
    namespace 'com.csync.hub'
    compileSdk 34

    defaultConfig {
        applicationId "com.csync.hub"
        minSdk 26
        targetSdk 34
        versionCode 53
        versionName "2.51"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

configurations.all {
    exclude group: 'org.jetbrains', module: 'annotations'
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
    implementation 'org.nanohttpd:nanohttpd:2.3.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'io.noties.markwon:core:4.6.2'
    implementation('io.noties.markwon:syntax-highlight:4.6.2') {
        exclude group: 'org.jetbrains', module: 'annotations'
    }
    implementation('io.noties:prism4j:2.0.0') {
        exclude group: 'org.jetbrains', module: 'annotations'
    }
    annotationProcessor 'io.noties:prism4j-bundler:2.0.0'
}
